// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkQuWAtbnm-Cs0IWA1cQodJ8Eq6sZmZLo',
    appId: '1:1057135661961:web:592056ca8c544512e5c758',
    messagingSenderId: '1057135661961',
    projectId: 'cloud-messaging-7188d',
    authDomain: 'cloud-messaging-7188d.firebaseapp.com',
    storageBucket: 'cloud-messaging-7188d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKI0IaDL6SdH3UcqWvJle4bLzi4Iopp1o',
    appId: '1:1057135661961:android:010224e6a2a2f963e5c758',
    messagingSenderId: '1057135661961',
    projectId: 'cloud-messaging-7188d',
    storageBucket: 'cloud-messaging-7188d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCXgJUC7lUaK6yJMRMAw84pXkVjwj9xrU',
    appId: '1:1057135661961:ios:54152a174b646ebae5c758',
    messagingSenderId: '1057135661961',
    projectId: 'cloud-messaging-7188d',
    storageBucket: 'cloud-messaging-7188d.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCXgJUC7lUaK6yJMRMAw84pXkVjwj9xrU',
    appId: '1:1057135661961:ios:54152a174b646ebae5c758',
    messagingSenderId: '1057135661961',
    projectId: 'cloud-messaging-7188d',
    storageBucket: 'cloud-messaging-7188d.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkQuWAtbnm-Cs0IWA1cQodJ8Eq6sZmZLo',
    appId: '1:1057135661961:web:836402eb27f23b4de5c758',
    messagingSenderId: '1057135661961',
    projectId: 'cloud-messaging-7188d',
    authDomain: 'cloud-messaging-7188d.firebaseapp.com',
    storageBucket: 'cloud-messaging-7188d.firebasestorage.app',
  );

}